# GitLab Tools Configuration
# This file contains default configuration values
# Environment variables will override these settings

gitlab:
  # API rate limiting (requests per second)
  rate_limit: 3
  
  # Request timeout in seconds
  timeout: 30
  
  # Number of retries for failed requests
  retry_count: 3
  
  # Number of items per page for pagination
  page_size: 100
  
  # Verify SSL certificates
  verify_ssl: true

features:
  # Enable dry-run mode by default
  dry_run: false
  
  # Create backups before destructive operations
  backup: true
  
  # Number of concurrent workers for parallel operations
  concurrent_workers: 5
  
  # Show progress bars for long operations
  show_progress: true
  
  # Enable colored output
  colored_output: true

branch_operations:
  # Default branch names for rename operations
  default_old_branch: "trunk"
  default_new_branch: "main"
  
  # Skip protected branches
  skip_protected: true
  
  # Update merge request target branches
  update_merge_requests: true

issue_operations:
  # Default labels to add to all issues
  default_labels: []
  
  # Template directory for issue templates
  template_dir: "templates/issues"
  
  # Add creation timestamp to issue description
  add_timestamp: true

# Groups to process (can be overridden via CLI)
groups:
  - name: "AI-ML-Services"
    filters:
      exclude_archived: true
      min_activity_days: 30
  
  - name: "Research Repos"
    filters:
      exclude_archived: true
      min_activity_days: 60

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  
  # Log file path (relative to project root)
  file: "logs/gitlab-tools.log"
  
  # Maximum log file size in MB
  max_size: 10
  
  # Number of backup files to keep
  backup_count: 5
  
  # Log format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Output configuration
output:
  # Default output directory for generated files
  directory: "outputs"
  
  # Formats to generate (json, csv, markdown)
  formats:
    - json
    - csv
    - markdown
  
  # Include timestamp in output filenames
  timestamp_format: "%Y%m%d_%H%M%S"